<Project>

  <PropertyGroup>
    <DSPVersion Condition=" '$(DSPVersion)' == '' ">160</DSPVersion>
    <OutputPath>../../../output/consumer/test/$(DSPVersion)/bin/$(Configuration)</OutputPath>
    <BaseIntermediateOutputPath>../../../output/consumer/test/$(DSPVersion)/obj/$(AssemblyName)</BaseIntermediateOutputPath>
  </PropertyGroup>

</Project>
